'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.9148
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Animal_Adoption.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property animal_shelter_clipart_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animal-shelter-clipart-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property portrait_of_kitten_and_puppy_on_grassy_field_at_royalty_free_image_936542938_1566225743() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portrait-of-kitten-and-puppy-on-grassy-field-at-royalty-free-image-936542938-1566"& _ 
                        "225743", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property portrait_of_kitten_and_puppy_on_grassy_field_at_royalty_free_image_936542938_1566225743__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portrait-of-kitten-and-puppy-on-grassy-field-at-royalty-free-image-936542938-1566"& _ 
                        "225743 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property portrait_of_kitten_and_puppy_on_grassy_field_at_royalty_free_image_936542938_15662257431() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("portrait-of-kitten-and-puppy-on-grassy-field-at-royalty-free-image-936542938-1566"& _ 
                        "2257431", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property website_BannerImg_02_Adoption_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("website_BannerImg_02_Adoption_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
